spring:
  application:
    name: spring-boot-client-demo
    
server:
  port: 8088
  context-path: 

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.132.128:8761/eureka/

ribbon:
  eureka:
    enabled: true      
      
  


